#!/usr/bin/env bash

dirs=()

# Check if the micro:bit is mounted to /mnt/D or /mnt/E.
if mountpoint -q /mnt/D; then
    echo "/mnt/D already mounted."
    dirs+=("D")
else
    if sudo mount -t drvfs D: /mnt/D; then
        echo "/mnt/D mounted successfully."
        dirs+=("D")
    else
        echo "Micro:bit not plugged in as D:"
    fi
fi

if mountpoint -q /mnt/E; then
    echo "/mnt/E already mounted."
    dirs+=("E")
else
    if sudo mount -t drvfs E: /mnt/E; then
        echo "/mnt/E mounted successfully."
        dirs+=("E")
    else
        echo "Micro:bit not plugged in as E:"
    fi
fi

if [ ${#dirs[@]} -eq 0 ]; then
    echo "So no, Micro:Bits?"
    exit 1
fi

# Run the python script to generate the MICROBIT.hex file.
python3 build.py $1 $2

# Move the output.hex onto the micro:bits.
for dir in ${dirs[@]}; do
    cp MICROBIT.hex /mnt/$dir
done

if [ $? -eq 0 ]; then
    echo "Flash: OK"
else
    echo "ERROR!"
fi
